// Constants and configuration objects for AIAnalyticsSettings component

// UI Text Constants
export const UI_TEXT = {
  HEADER: {
    TITLE: 'AI and Analytics Settings',
    SUBTITLE: 'Configure AI features, analytics, and intelligence settings',
  },
  BUTTONS: {
    RESET: 'Reset',
    SAVE: 'Save Settings',
    SAVING: 'Saving...',
  },
  MESSAGES: {
    LOADING: 'Loading AI settings...',
    FACILITY_NOT_AVAILABLE: 'Facility not available. Please select a facility first.',
    FAILED_TO_LOAD: 'Failed to load AI settings. Please try refreshing the page.',
    SAVE_SUCCESS: 'AI settings saved and applied successfully!',
    SAVE_ERROR: 'Failed to save AI settings',
    RESET_SUCCESS: 'Settings reset to defaults',
    RESET_ERROR: 'Failed to reset settings',
  },
  SECTIONS: {
    AI_SERVICE_STATUS: 'AI Service Status',
    ENABLE_AI_FEATURES: 'Enable AI Features',
    AI_FEATURES: 'AI Features',
    ANALYTICS_CONFIGURATION: 'Analytics Configuration',
    INTELLIGENCE_SETTINGS: 'Intelligence Settings',
    PERFORMANCE_MONITORING: 'Performance Monitoring',
    DATA_PRIVACY_SECURITY: 'Data Privacy & Security',
    INTEGRATION_SETTINGS: 'Integration Settings',
    USER_EXPERIENCE: 'User Experience',
  },
  FORM_GROUPS: {
    COMPUTER_VISION: 'Computer Vision',
    PREDICTIVE_ANALYTICS: 'Predictive Analytics',
    SMART_WORKFLOW: 'Smart Workflow',
    DATA_COLLECTION: 'Data Collection',
    REPORTING_EXPORT: 'Reporting & Export',
    RISK_ALERTS: 'Risk & Alerts',
    AI_INSIGHTS: 'AI Insights',
    QUALITY_METRICS: 'Quality Metrics',
    OPTIMIZATION: 'Optimization',
    PRIVACY_CONTROLS: 'Privacy Controls',
    SECURITY_FEATURES: 'Security Features',
    EXTERNAL_SERVICES: 'External Services',
    SYSTEM_HEALTH: 'System Health',
    AI_ASSISTANCE: 'AI Assistance',
    INTERFACE_HELP: 'Interface & Help',
  },
  TOGGLE_LABELS: {
    TOOL_CONDITION_ASSESSMENT: 'Tool Condition Assessment',
    BARCODE_QUALITY_DETECTION: 'Barcode Quality Detection',
    DAMAGE_DETECTION: 'Damage Detection',
    CYCLE_OPTIMIZATION: 'Cycle Optimization',
    FAILURE_PREDICTION: 'Failure Prediction',
    EFFICIENCY_OPTIMIZATION: 'Efficiency Optimization',
    INTELLIGENT_WORKFLOW_SELECTION: 'Intelligent Workflow Selection',
    AUTOMATED_PROBLEM_DETECTION: 'Automated Problem Detection',
    DATA_COLLECTION: 'Data Collection',
    REAL_TIME_UPDATES: 'Real-time Updates',
    HISTORICAL_DATA_RETENTION: 'Historical Data Retention',
    EXPORT_CAPABILITIES: 'Export Capabilities',
    DASHBOARD_CUSTOMIZATION: 'Dashboard Customization',
    RISK_ASSESSMENT: 'Risk Assessment',
    ALERT_SYSTEM: 'Alert System',
    ESCALATION_RULES: 'Escalation Rules',
    AI_RECOMMENDATIONS: 'AI Recommendations',
    OPTIMIZATION_TIPS: 'Optimization Tips',
    ACCURACY_TRACKING: 'Accuracy Tracking',
    RESPONSE_TIME_MONITORING: 'Response Time Monitoring',
    ERROR_RATE_TRACKING: 'Error Rate Tracking',
    PERFORMANCE_ALERTS: 'Performance Alerts',
    MODEL_HEALTH_MONITORING: 'Model Health Monitoring',
    DATA_ANONYMIZATION: 'Data Anonymization',
    THIRD_PARTY_PERMISSIONS: 'Third-party Permissions',
    COMPLIANCE_MONITORING: 'Compliance Monitoring',
    ENCRYPTION: 'Encryption',
    ACCESS_CONTROL: 'Access Control',
    EXTERNAL_SERVICES: 'External Services',
    API_RATE_LIMITING: 'API Rate Limiting',
    WEBHOOK_ENDPOINTS: 'Webhook Endpoints',
    HEALTH_MONITORING: 'Health Monitoring',
    SYNC_SCHEDULING: 'Sync Scheduling',
    AI_SUGGESTIONS: 'AI Suggestions',
    LEARNING_PATHS: 'Learning Paths',
    PERSONALIZATION: 'Personalization',
    ACCESSIBILITY_FEATURES: 'Accessibility Features',
    SMART_HELP_SYSTEM: 'Smart Help System',
  },
  DESCRIPTIONS: {
    MASTER_AI_TOGGLE: 'Master toggle for all AI-powered features across the system',
    TOOL_CONDITION_ASSESSMENT: 'AI-powered tool wear and condition analysis',
    BARCODE_QUALITY_DETECTION: 'Automatic barcode readability assessment',
    DAMAGE_DETECTION: 'AI detection of tool damage and defects',
    CYCLE_OPTIMIZATION: 'AI-powered sterilization cycle optimization',
    FAILURE_PREDICTION: 'Predictive maintenance and failure alerts',
    EFFICIENCY_OPTIMIZATION: 'AI-driven workflow efficiency improvements',
    INTELLIGENT_WORKFLOW_SELECTION: 'AI-powered workflow recommendations',
    AUTOMATED_PROBLEM_DETECTION: 'AI detection of workflow issues',
    DATA_COLLECTION: 'Enable comprehensive data collection',
    REAL_TIME_UPDATES: 'Live analytics and dashboard updates',
    HISTORICAL_DATA_RETENTION: 'Long-term data storage and analysis',
    EXPORT_CAPABILITIES: 'PDF, CSV, and Excel export options',
    DASHBOARD_CUSTOMIZATION: 'Customizable analytics dashboards',
    RISK_ASSESSMENT: 'AI-powered risk analysis and scoring',
    ALERT_SYSTEM: 'Smart notification and alert system',
    ESCALATION_RULES: 'Automatic alert escalation based on priority',
    AI_RECOMMENDATIONS: 'Intelligent recommendations and suggestions',
    OPTIMIZATION_TIPS: 'AI-generated optimization suggestions',
    ACCURACY_TRACKING: 'Monitor AI prediction accuracy',
    RESPONSE_TIME_MONITORING: 'Track AI response times and performance',
    ERROR_RATE_TRACKING: 'Monitor and track error rates',
    PERFORMANCE_ALERTS: 'Alerts for performance issues',
    MODEL_HEALTH_MONITORING: 'AI model performance and health tracking',
    DATA_ANONYMIZATION: 'Automatically anonymize sensitive data',
    THIRD_PARTY_PERMISSIONS: 'Control third-party AI service access',
    COMPLIANCE_MONITORING: 'Monitor regulatory compliance',
    ENCRYPTION: 'End-to-end data encryption',
    ACCESS_CONTROL: 'Role-based access control for AI features',
    EXTERNAL_SERVICES: 'Connect to external AI and analytics services',
    API_RATE_LIMITING: 'Control API usage and rate limits',
    WEBHOOK_ENDPOINTS: 'Enable webhook notifications and integrations',
    HEALTH_MONITORING: 'Monitor integration system health',
    SYNC_SCHEDULING: 'Automated data synchronization',
    AI_SUGGESTIONS: 'Contextual AI-powered suggestions',
    LEARNING_PATHS: 'Personalized AI learning recommendations',
    PERSONALIZATION: 'AI-driven interface personalization',
    ACCESSIBILITY_FEATURES: 'AI-powered accessibility enhancements',
    SMART_HELP_SYSTEM: 'AI-powered contextual help and guidance',
  },
  STATUS: {
    ACTIVE: 'Active',
    INACTIVE: 'Inactive',
  },
} as const;

// Timeout Constants
export const TIMEOUTS = {
  MESSAGE_DISPLAY: 5000,
  RESET_MESSAGE_DISPLAY: 3000,
} as const;

// CSS Class Constants
export const CSS_CLASSES = {
  PRIMARY_COLOR: '#4ECDC4',
  PRIMARY_COLOR_HOVER: '#3db8b0',
  PRIMARY_COLOR_RING: '#4ECDC4/20',
} as const;
