// Mock checklist data
import { Checklist } from '../types';

export const mockChecklists: Checklist[] = [
  {
    id: 'checklist-001',
    name: 'Operating Room Deep Clean',
    description: 'Comprehensive cleaning protocol for operating rooms',
    isActive: true,
    status: 'published',
    category: 'environmental_cleaning',
    items: [
      {
        id: 'item-001',
        description: 'Remove all medical equipment and supplies',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-002',
        description: 'Disinfect all surfaces with hospital-grade cleaner',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-003',
        description: 'Clean and sanitize surgical lights',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-004',
        description: 'Mop floor with disinfectant solution',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-005',
        description: 'Check and replace air filters',
        isRequired: false,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'checklist-002',
    name: 'ICU Room Sanitization',
    description: 'Specialized cleaning for intensive care units',
    isActive: true,
    status: 'published',
    category: 'environmental_cleaning',
    items: [
      {
        id: 'item-006',
        description: 'Wear full PPE including gown, gloves, and mask',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-007',
        description: 'Disinfect all high-touch surfaces',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-008',
        description: 'Clean and sanitize medical equipment',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-009',
        description: 'Replace linens and bedding',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-010',
        description: 'Dispose of biohazard waste properly',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'checklist-003',
    name: 'Emergency Room Quick Clean',
    description: 'Rapid cleaning protocol for emergency rooms',
    isActive: true,
    status: 'published',
    category: 'environmental_cleaning',
    items: [
      {
        id: 'item-011',
        description: 'Remove visible debris and waste',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-012',
        description: 'Disinfect patient care areas',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-013',
        description: 'Restock essential supplies',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-014',
        description: 'Check emergency equipment',
        isRequired: false,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'checklist-004',
    name: 'Public Area Maintenance',
    description: 'General cleaning for public spaces',
    isActive: true,
    status: 'published',
    category: 'environmental_cleaning',
    items: [
      {
        id: 'item-015',
        description: 'Vacuum carpets and rugs',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-016',
        description: 'Clean and disinfect seating areas',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-017',
        description: 'Empty trash receptacles',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-018',
        description: 'Clean windows and glass surfaces',
        isRequired: false,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'checklist-005',
    name: 'Set-up and Takedown',
    description:
      'Comprehensive checklist for room preparation and cleanup procedures',
    isActive: true,
    status: 'published',
    category: 'environmental_cleaning',
    items: [
      {
        id: 'item-025',
        description: 'Verify room is empty and secure',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-026',
        description: 'Set up cleaning equipment and supplies',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-027',
        description: 'Position safety barriers and warning signs',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-028',
        description: 'Check ventilation and air circulation',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-029',
        description: 'Prepare disinfectant solutions according to protocol',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-030',
        description: 'Document room condition before cleaning',
        isRequired: false,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-031',
        description: 'Remove all cleaning equipment and supplies',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-032',
        description: 'Remove safety barriers and warning signs',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-033',
        description: 'Verify room is ready for next use',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-034',
        description: 'Update room status in system',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-035',
        description: 'Complete final inspection checklist',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-036',
        description: 'Document completion time and cleaner details',
        isRequired: false,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'checklist-006',
    name: 'Per Patient Cleaning',
    description:
      'Comprehensive cleaning protocol required after each patient use',
    isActive: true,
    status: 'published',
    category: 'environmental_cleaning',
    items: [
      {
        id: 'item-037',
        description: 'Remove all patient-specific items and linens',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-038',
        description: 'Dispose of biohazard waste in designated containers',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-039',
        description: 'Clean and disinfect all patient contact surfaces',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-040',
        description: 'Sanitize medical equipment used during patient care',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-041',
        description: 'Clean and disinfect bed rails, headboard, and footboard',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-042',
        description: 'Sanitize call button, TV remote, and bedside controls',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-043',
        description: 'Clean and disinfect bathroom fixtures and surfaces',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-044',
        description: 'Replace all linens with clean, sterile bedding',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-045',
        description: 'Clean and disinfect floor surfaces thoroughly',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-046',
        description: 'Check and replace air filters if contaminated',
        isRequired: false,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-047',
        description: 'Verify room ventilation is functioning properly',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-048',
        description: 'Document cleaning completion and room readiness',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-049',
        description: 'Update room status to ready for next patient',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
      {
        id: 'item-050',
        description: 'Perform final visual inspection for cleanliness',
        isRequired: true,
        isCompleted: false,
        completedBy: undefined,
        completedAt: undefined,
      },
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
];
