[functions.audit-management]
verify_jwt = false
import_map = "../auth-login/deno.json"

[functions.audit-management.env]
# Audit management configuration
ENABLE_AUDIT_MONITORING = "true"
ENABLE_AUDIT_SIGNATURES = "true"
ENABLE_AUDIT_CHAINING = "true"
ENABLE_AUDIT_RETENTION = "true"
AUDIT_RETENTION_DAYS = "2555"
MAX_EVENTS_PER_CHAIN = "10000"
AUDIT_SIGNATURE_KEY = "change-in-production"
AUDIT_HASH_ALGORITHM = "sha256"
