export const mockTools = [
  {
    id: '1',
    name: 'Scalpel Handle #3',
    barcode: 'SCAL001',
    currentPhase: 'complete',
    category: 'Surgical',
  },
  {
    id: '2',
    name: 'Forceps 5"',
    barcode: 'FORC001',
    currentPhase: 'processing',
    category: 'Surgical',
  },
  {
    id: '3',
    name: 'Retractor Set',
    barcode: 'RETR001',
    currentPhase: 'complete',
    category: 'Surgical',
  },
  {
    id: '4',
    name: 'Dental Mirror',
    barcode: 'DENT001',
    currentPhase: 'processing',
    category: 'Dental',
  },
];

export const inventoryData = [
  {
    item: 'Scalpel Handle #3',
    category: 'Surgical',
    toolId: 'T-001',
    location: 'OR 1',
    p2Status: 'clean',
    cost: 45.0,
  },
  {
    item: 'Forceps 5"',
    category: 'Surgical',
    toolId: 'T-002',
    location: 'OR 2',
    p2Status: 'dirty',
    cost: 35.0,
  },
  {
    item: 'Retractor Set',
    category: 'Surgical',
    toolId: 'T-003',
    location: 'OR 1',
    p2Status: 'bath1',
    cost: 150.0,
  },
  {
    item: 'Surgical Scissors',
    category: 'Surgical',
    toolId: 'T-004',
    location: 'OR 3',
    p2Status: 'clean',
    cost: 85.0,
  },
  {
    item: 'Hemostat',
    category: 'Surgical',
    toolId: 'T-005',
    location: 'OR 2',
    p2Status: 'dirty',
    cost: 65.0,
  },
  {
    item: 'Needle Holder',
    category: 'Surgical',
    toolId: 'T-006',
    location: 'OR 1',
    p2Status: 'bath1',
    cost: 95.0,
  },
  {
    item: 'Suture Kit',
    category: 'Surgical',
    toolId: 'T-007',
    location: 'OR 3',
    p2Status: 'clean',
    cost: 120.0,
  },
  {
    item: 'Dental Mirror',
    category: 'Dental',
    toolId: 'T-008',
    location: 'Dental Suite',
    p2Status: 'clean',
    cost: 25.0,
  },
];

export const suppliesData = [
  {
    item: 'Gauze',
    category: 'Supplies',
    supplyId: 'S-001',
    location: 'Supply Room',
    quantity: 500,
    expiration: '2025-12-31',
    cost: 25.0,
  },
  {
    item: 'Surgical Tape',
    category: 'Supplies',
    supplyId: 'S-002',
    location: 'Supply Room',
    quantity: 200,
    expiration: '2025-06-30',
    cost: 15.0,
  },
  {
    item: 'Syringe',
    category: 'Supplies',
    supplyId: 'S-003',
    location: 'Supply Room',
    quantity: 150,
    expiration: '2025-03-15',
    cost: 15.75,
  },
  {
    item: 'Alcohol Wipes',
    category: 'Supplies',
    supplyId: 'S-004',
    location: 'Supply Room',
    quantity: 300,
    expiration: '2025-08-20',
    cost: 12.5,
  },
  {
    item: 'Bandages',
    category: 'Supplies',
    supplyId: 'S-005',
    location: 'Supply Room',
    quantity: 400,
    expiration: '2026-01-15',
    cost: 18.25,
  },
  {
    item: 'Surgical Masks',
    category: 'Supplies',
    supplyId: 'S-006',
    location: 'Supply Room',
    quantity: 1000,
    expiration: '2025-10-30',
    cost: 8.75,
  },
];

export const equipmentData = [
  {
    item: 'Autoclave Machine',
    category: 'Equipment',
    equipmentId: 'E-001',
    location: 'Sterilization Room',
    status: 'operational',
    lastServiced: '2024-01-15',
    cost: 5000.0,
  },
  {
    item: 'Ultrasonic Cleaner',
    category: 'Equipment',
    equipmentId: 'E-002',
    location: 'Sterilization Room',
    status: 'maintenance',
    lastServiced: '2024-02-01',
    cost: 2500.0,
  },
  {
    item: 'Monitor',
    category: 'Equipment',
    equipmentId: 'E-003',
    location: 'ICU',
    status: 'operational',
    lastServiced: '2024-01-10',
    cost: 2500.0,
  },
  {
    item: 'Defibrillator',
    category: 'Equipment',
    equipmentId: 'E-004',
    location: 'ER',
    status: 'maintenance',
    lastServiced: '2023-11-05',
    cost: 3500.0,
  },
  {
    item: 'Ventilator',
    category: 'Equipment',
    equipmentId: 'E-005',
    location: 'ICU',
    status: 'operational',
    lastServiced: '2024-03-01',
    cost: 8000.0,
  },
  {
    item: 'X-Ray Machine',
    category: 'Equipment',
    equipmentId: 'E-006',
    location: 'Radiology',
    status: 'operational',
    lastServiced: '2024-02-15',
    cost: 15000.0,
  },
];

export const officeHardwareData = [
  {
    item: 'Computer Monitor',
    category: 'Office Hardware',
    hardwareId: 'H-001',
    location: 'Admin Office',
    status: 'active',
    warranty: '2025-12-31',
    cost: 300.0,
  },
  {
    item: 'Printer',
    category: 'Office Hardware',
    hardwareId: 'H-002',
    location: 'Admin Office',
    status: 'active',
    warranty: '2024-08-15',
    cost: 450.0,
  },
  {
    item: 'Desktop Computer',
    category: 'Office Hardware',
    hardwareId: 'H-003',
    location: 'Reception',
    status: 'offline',
    warranty: '2024-09-15',
    cost: 1200.0,
  },
  {
    item: 'Laptop',
    category: 'Office Hardware',
    hardwareId: 'H-004',
    location: 'Admin Office',
    status: 'active',
    warranty: '2025-06-30',
    cost: 1500.0,
  },
  {
    item: 'Scanner',
    category: 'Office Hardware',
    hardwareId: 'H-005',
    location: 'Admin Office',
    status: 'active',
    warranty: '2025-03-20',
    cost: 350.0,
  },
  {
    item: 'Network Switch',
    category: 'Office Hardware',
    hardwareId: 'H-006',
    location: 'IT Room',
    status: 'active',
    warranty: '2026-01-10',
    cost: 800.0,
  },
];
