name: Simple CI

on:
  push:
    branches: [main, master, newmainbranch3.0, feature/gamification-challenges]
  pull_request:
    branches: [main, master, newmainbranch3.0, feature/gamification-challenges]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build (required)
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          
      - name: Lint (optional - won't fail CI)
        run: npm run lint || echo "Lint issues found but not blocking"
        continue-on-error: true
        
      - name: Quick test (optional - won't fail CI)
        run: npm run test:unit || echo "Some tests failed but not blocking"
        continue-on-error: true
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
